import localFont from "next/font/local";
import "./globals.css";
//import our clerk provider
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  UserButton,
  SignedOut,
} from "@clerk/nextjs";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PostForm from "@/components/PostFormClient";
import { dark } from "@clerk/themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    //im going to wrap my whole app with clerk provider
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          <SignedIn>
            <PostForm />
          </SignedIn>
          <Footer />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
